APP_VERSION = "1.6.0"
EVIDENCE_SCHEMA_VERSION = "sentinel-evidence-v1"
STATIC_RULESET_VERSION = "sentinel-rules-2026.07"
PATCH_VALIDATOR_VERSION = "sentinel-patch-v2"
POLICY_VERSION = "sentinel-gate-v1"
